language: node_js
node_js:
    - "6.1"

before_script:
    - npm install
    - cd app
    - npm install -g bower
    - bower cache clean
    - bower install --force
    - cd ./..    
    - gulp clone-plugins
    - gulp packageCorePlugins
    - npm run plugin-build
    - npm run build
    
script:
    - npm run apptest
    - npm run testpluginframework