- name: Copy zip file to server
  copy: src=content-editor.zip dest=/home/{{user}}/ owner={{user}} group={{user}} mode=0774

- name: Create Content-Editor directory
  file: path=/home/{{user}}/Content-Editor owner={{user}} group={{user}} state=directory

- name: Status of AT Service
  command: forever list
  register: forever_status

- name: Stop AT Service
  command: forever stop app.js
  when: "forever_status.stdout.find('No forever processes running') == -1"
  args:
    chdir: /home/{{user}}/Content-Editor
  
- name: Unarchive zip file
  unarchive: src=/home/{{user}}/content-editor.zip dest=/home/{{user}}/Content-Editor/ copy=no owner={{user}} group={{user}} mode=0774

- name: Install npm packages
  command: "npm install"
  args:
    chdir: /home/{{user}}/Content-Editor

- name: Install bower packages
  command: "bower install"
  args:
    chdir: /home/{{user}}/Content-Editor/app

- name: Start AT Service
  command: forever start app.js
  args:
    chdir: /home/{{user}}/Content-Editor  