- name: Copy zip file to server
  copy: src=content-editor.zip dest={{user_home}}/ owner={{user}} group={{user}} mode=0774

- name: Create Content-Editor directory
  file: path={{at_home}} owner={{user}} group={{user}} state=directory

- name: Status of AT Service
  command: forever list
  register: forever_status

- name: Stop AT Service
  command: forever stop app.js
  when: "forever_status.stdout.find('No forever processes running') == -1"
  args:
    chdir: "{{at_home}}"
  
- name: Unarchive zip file
  unarchive: src={{user_home}}/content-editor.zip dest={{at_home}} copy=no owner={{user}} group={{user}} mode=0774

- name: Install npm packages
  command: "npm install"
  args:
    chdir: "{{at_home}}"

- name: Install bower packages
  command: "bower install"
  args:
    chdir: "{{at_home}}/content-editor"

- name: Start AT Service
  command: forever start app.js
  args:
    chdir: "{{at_home}}"